const questions = [
    {"question": "What is the difference between a pointer and a reference in C++?", "answer": "A pointer is a variable that stores a memory address, while a reference is an alias for an existing variable and cannot be reassigned."},
    {"question": "Which keyword is used to allocate dynamic memory in C++?", "answer": "new"},
    {"question": "In Unreal Engine, what is the primary scripting language used for gameplay logic?", "answer": "Blueprints and C++"},
    {"question": "What is the purpose of the GameMode class in Unreal Engine?", "answer": "It defines the rules and flow of the game, including player spawn, game state, and win/loss conditions."},
    {"question": "What does HTML stand for?", "answer": "HyperText Markup Language"},
    {"question": "Which CSS property is used to change the text color of an element?", "answer": "color"},
    {"question": "What command is used to enter privileged EXEC mode in Cisco IOS?", "answer": "enable"},
    {"question": "Which Cisco IOS command displays the current running configuration?", "answer": "show running-config"},
    {"question": "Which SQL statement is used to retrieve data from a database?", "answer": "SELECT"},
    {"question": "What is the primary key in MySQL?", "answer": "A unique identifier for each record in a table."},
    {"question": "Which command is used to list all files in a directory in Linux?", "answer": "ls"},
    {"question": "How do you change file permissions in Unix?", "answer": "Using the chmod command."},
    {"question": "What is the default port for SSH?", "answer": "22"},
    {"question": "Which protocol is used to assign IP addresses dynamically?", "answer": "DHCP (Dynamic Host Configuration Protocol)"},
    {"question": "What is the function of the ARP protocol?", "answer": "It maps an IP address to a MAC address on a local network."},
    {"question": "Which database engine is used by default in MySQL?", "answer": "InnoDB"},
    {"question": "What is the difference between TCP and UDP?", "answer": "TCP is connection-oriented and reliable, while UDP is connectionless and faster but less reliable."},
    {"question": "How do you create a new branch in Git?", "answer": "git branch <branch-name>"},
    {"question": "What does the 'mkdir' command do in Linux?", "answer": "Creates a new directory."},
    {"question": "Which Linux command is used to find the IP address of a system?", "answer": "ip a or ifconfig"},
    {"question": "What is NAT in networking?", "answer": "Network Address Translation, used to remap private IP addresses to a public IP address."},
    {"question": "What does the 'grep' command do in Unix/Linux?", "answer": "Searches for a specific pattern in a file or output."},
    {"question": "Which CSS property controls the layout of elements using a flexible box model?", "answer": "display: flex"},
    {"question": "What is a foreign key in MySQL?", "answer": "A field in a table that establishes a relationship with the primary key of another table."},
    {"question": "How do you restart the networking service in Linux?", "answer": "sudo systemctl restart networking"},
    {"question": "Which Unreal Engine class is used to create an interactive object in the game world?", "answer": "AActor"},
    {"question": "What is the difference between GET and POST methods in HTTP?", "answer": "GET requests data from a server, while POST submits data to be processed."},
    {"question": "What does VLAN stand for?", "answer": "Virtual Local Area Network"},
    {"question": "What is the purpose of the sudo command in Linux?", "answer": "It allows a user to execute commands with superuser privileges."},
    {"question": "What is a segmentation fault in C/C++?", "answer": "A runtime error that occurs when a program accesses restricted or invalid memory locations."},
    {"question": "How do you declare a pure virtual function in C++?", "answer": "By assigning 0 to a virtual function inside a base class, e.g., virtual void func() = 0;"},
    {"question": "What is the purpose of the 'BlueprintCallable' specifier in Unreal Engine?", "answer": "It allows a C++ function to be called from a Blueprint script."},
    {"question": "What is the difference between 'let', 'var', and 'const' in JavaScript?", "answer": "'var' is function-scoped, 'let' is block-scoped, and 'const' is block-scoped but immutable."},
    {"question": "Which command is used to view the routing table on a Cisco router?", "answer": "show ip route"},
    {"question": "What does the 'JOIN' clause do in SQL?", "answer": "It combines rows from two or more tables based on a related column."},
    {"question": "What is the default shell in most Linux distributions?", "answer": "Bash (Bourne Again Shell)"},
    {"question": "Which Unix command is used to display the last 10 lines of a file?", "answer": "tail -10 <filename>"},
    {"question": "What is the purpose of the 'ping' command in networking?", "answer": "It tests connectivity between two devices using ICMP echo requests."},
    {"question": "What is the difference between IPv4 and IPv6?", "answer": "IPv4 uses 32-bit addresses and supports ~4.3 billion devices, while IPv6 uses 128-bit addresses and supports a virtually unlimited number of devices."}
];
console.log(`${questions.length} questions are loaded!`);